### ISSUE TITLE
SonarQube issue: Use a primitive boolean expression

### ISSUE THREAD

**Issue by gabscastilho** [jaymesakae/ES2_2023-2_DSMEditor#12]
Avoid using boxed "Boolean" types directly in boolean expressions.

https://sonarcloud.io/project/issues?resolved=false&id=anaconrado_ES2_2023-2_DSMEditor&open=AY2EtOXEh8wQcJ1sKHVr

Responsável: Gabrielly
Revisor(a): Jayme

**Comment by gabscastilho** [comment]
Novo responsável: @augustodsgv 
Revisor(a): Gabrielly

**Comment by augustodsgv** [comment]
Esta issue não faz muito sentido: o sonarcloud diz que deve-se usar um operador de comparação para uma variável que já é booleana, como `if(bool_var == true)`. Além disso, quando se faz esse fix recomendado, ele gera um novo problema de code smells por comparação inválida com booleano
