### ISSUE TITLE
Correção de problemas

### ISSUE THREAD

**Issue by jaymesakae** [jaymesakae/ES2_2023-2_DSMEditor#7]
Corrigir 4 problemas ou Warnings apontados pelo Sonar

Responsável: Todos os membros
Revisor(a): Todos os membros

**Comment by gabscastilho** [comment]
Resolve #9

**Comment by jaymesakae** [comment]
Issue 14
Responsável: Jayme Furuyama
Revisor(a): A definir

**Comment by gabscastilho** [comment]
Todos resolveram.
